imports:
    - { resource: config.yml }


#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            max_files: 30
            level: debug
        telegram:
            type: service
            id: app.log.telegram_handler
            action_level: error
        console:
            type:  console
