imports:
    - { resource: config_dev.yml }


doctrine:
    dbal:
        # todo move to new environment variables: https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
        dbname:   "%env(SYMFONY__TEST_DATABASE_NAME)%"
        port:     "%env(SYMFONY__TEST_DATABASE_PORT)%"
        user:     "%env(SYMFONY__TEST_DATABASE_USER)%"
        password: "%env(SYMFONY__TEST_DATABASE_PASSWORD)%"

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
