imports:
    - { resource: config.yml }


#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      rotated_file
        rotated_file:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            max_files: 30
            level: debug
        # for commands
        console:
            type: console
