index:
    path:     /
    defaults: { _controller: SkobkinPointToolsBundle:Main:index }
    methods: [POST, GET]

telegram_webhook:
    path:     /telegram/webhook/{token}
    defaults: { _controller: SkobkinPointToolsBundle:Telegram/WebHook:receiveUpdate, _format: json }
    methods:  [POST]
    requirements:
        token: '\d+\:[\w-]+'
        _format: json

user_search_ajax:
    path:     /ajax/users/search/{login}
    defaults: { _controller: SkobkinPointToolsBundle:Main:searchUserAjax, _format: json }
    methods: [GET]
    requirements:
        login: '[\w-]*'
        _format: json

user_show:
    path:     /user/{login}
    defaults: { _controller: SkobkinPointToolsBundle:User:show }
    methods: [GET]
    requirements:
        login: '[\w-]+'

statistics:
    path:     /users/top
    defaults: { _controller: SkobkinPointToolsBundle:User:top }
    methods: [GET]

events_last:
    path:     /events/last
    defaults: { _controller: SkobkinPointToolsBundle:Events:last }
    methods: [GET]

post_show:
    path:     /{id}
    defaults: { _controller: SkobkinPointToolsBundle:Post:show }
    methods: [GET]
    requirements:
        id: '[a-z]+'

api_public:
    resource: '@SkobkinPointToolsBundle/Resources/config/api/public.yml'
    prefix:   /api/v1

api_crawler:
    resource: '@SkobkinPointToolsBundle/Resources/config/api/crawler.yml'
    prefix:   /api/crawler
