index:
    path:     /
    defaults: { _controller: SkobkinPointToolsBundle:Main:index }

user_search:
    path:     /search
    defaults: { _controller: SkobkinPointToolsBundle:User:searchUser }
    methods: [POST]

user_show:
    path:     /user/{login}
    defaults: { _controller: SkobkinPointToolsBundle:User:show }
    requirements:
        login: "[\w-]+"

users_top:
    path:     /top
    defaults: { _controller: SkobkinPointToolsBundle:User:top }

events_last:
    path:     /last
    defaults: { _controller: SkobkinPointToolsBundle:Events:last }

api_public:
    resource: "@SkobkinPointToolsBundle/Resources/config/api/public.yml"
    prefix:   /api/v1

api_crawler:
    resource: "@SkobkinPointToolsBundle/Resources/config/api/crawler.yml"
    prefix:   /api/crawler