index:
    path:     /
    defaults: { _controller: SkobkinPointToolsBundle:Main:index }

user_search:
    path:     /search
    defaults: { _controller: SkobkinPointToolsBundle:User:searchUser }
    methods: [POST]

user_show:
    path:     /user/{login}
    defaults: { _controller: SkobkinPointToolsBundle:User:show }
    requirements:
        login: "[\w-]+"

users_top:
    path:     /top
    defaults: { _controller: SkobkinPointToolsBundle:User:top }