services:
    # Guzzle 6 client for Telegram
    point_tools.http.telegram_client:
        class: GuzzleHttp\Client
        arguments: [{ timeout: 3.0 }]
        tags:
            - { name: csa_guzzle.client }

    # Guzzle 5 client for Point API
    # TODO upgrade and remove misd bundle
    skobkin_point_tools.http_client:
        class: %guzzle.client.class%
        arguments: [ "%point_base_url%" ]
        tags:
            - { name: guzzle.client }

    skobkin_point_tools.api_user:
        class: Skobkin\Bundle\PointToolsBundle\Service\UserApi
        arguments:
            - @skobkin_point_tools.http_client
            - "%point_use_https%"
            - "%point_api_base_url%"
            - @doctrine.orm.entity_manager

    skobkin_point_tools.api_post:
        class: Skobkin\Bundle\PointToolsBundle\Service\PostApi
        arguments:
            - @skobkin_point_tools.http_client
            - "%point_use_https%"
            - "%point_api_base_url%"
            - @skobkin__point_tools.service_factory.post_factory

    skobkin_point_tools.subscriptions_manager:
        class: Skobkin\Bundle\PointToolsBundle\Service\SubscriptionsManager
        arguments: [ @doctrine.orm.entity_manager ]

    skobkin__point_tools.service_factory.user_factory:
        class: Skobkin\Bundle\PointToolsBundle\Service\Factory\UserFactory
        arguments: [ @doctrine.orm.entity_manager ]

    skobkin__point_tools.service_factory.comment_factory:
        class: Skobkin\Bundle\PointToolsBundle\Service\Factory\Blogs\CommentFactory
        arguments: [ @doctrine.orm.entity_manager, @skobkin__point_tools.service_factory.user_factory ]

    skobkin__point_tools.service_factory.tag_factory:
        class: Skobkin\Bundle\PointToolsBundle\Service\Factory\Blogs\TagFactory
        arguments: [ @logger, @doctrine.orm.entity_manager ]

    skobkin__point_tools.service_factory.file_factory:
        class: Skobkin\Bundle\PointToolsBundle\Service\Factory\Blogs\FileFactory
        arguments: [ @logger, @doctrine.orm.entity_manager ]

    skobkin__point_tools.service_factory.post_factory:
        class: Skobkin\Bundle\PointToolsBundle\Service\Factory\Blogs\PostFactory
        arguments:
            - @logger
            - @doctrine.orm.entity_manager
            - @skobkin__point_tools.service_factory.user_factory
            - @skobkin__point_tools.service_factory.file_factory
            - @skobkin__point_tools.service_factory.comment_factory
            - @skobkin__point_tools.service_factory.tag_factory

    # Custom Markdown parser
    markdown.parser.point:
        class: Skobkin\Bundle\PointToolsBundle\Service\Markdown\PointParser
        arguments:
            - []
            - @router
        tags:
            - { name: markdown.parser }

    # Event listener
    point_tools.event_listener.user_rename_subscriber:
        class: Skobkin\Bundle\PointToolsBundle\EventListener\UserRenameSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # Twig extensions
    point_tools.twig.point_avatar_extension:
        class: Skobkin\Bundle\PointToolsBundle\Twig\PointUserExtension
        public: false
        arguments: ['@skobkin_point_tools.api_user']
        tags:
            - { name: twig.extension }

    # Telegram API client
    point_tools.telegram.api_client:
        class: unreal4u\TelegramAPI\TgLog
        arguments: [%telegram_token%, @logger, @point_tools.http.telegram_client]

    # Telegram simple message sender
    point_tools.telegram.simple_sender:
        class: Skobkin\Bundle\PointToolsBundle\Service\Telegram\SimpleSender
        arguments: [@point_tools.telegram.api_client]

    # Telegram command processor
    point_tools.telegram.update_processor:
        class: Skobkin\Bundle\PointToolsBundle\Service\Telegram\IncomingUpdateProcessor
        arguments: [%point_id%, @point_tools.telegram.api_client, @doctrine.orm.entity_manager, @twig]