Skobkin\Bundle\PointToolsBundle\DTO\Api\Post:
    exclusion_policy: none
    access_type: public_method
    properties:
        id:
            type: string
            #groups: []
        tags:
            type: 'array<string>'
        files:
            type: 'array<string>'
        author:
            type: Skobkin\Bundle\PointToolsBundle\DTO\Api\User
            max_depth: 1
        text:
            type: string
        created:
            type: string
        type:
            type: string
        private:
            type: boolean

    #callback_methods:
    #    post_deserialize: [foo, bar]
