Skobkin\Bundle\PointToolsBundle\DTO\Api\PostsPage:
    exclusion_policy: none
    access_type: public_method
    properties:
        posts:
            type: 'array<Skobkin\Bundle\PointToolsBundle\DTO\Api\MetaPost>'
            max_depth: 3
        hasNext:
            serialized_name: 'has_next'
            type: boolean
