# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # TODO: fix retrieval
            # Telegram Bot API
            $telegramToken: ''
            $debugEnabled: '%kernel.debug%'
            # Point API
            $pointDomain: 'point.im'
            $pointScheme: 'https'
            $pointApiDelay: 5000
            $pointAppUserId: ''
            $pointApiClient: '@app.point.http_client'
            # Crawler API
            $crawlerToken: ''

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # HTTP client for Point API
    app.point.http_client:
        class: Symfony\Component\HttpClient\HttpClient
        factory: [null, 'create']
        arguments:
            base_uri: '%point_base_url%'
            timeout: 5.0
