# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # Point Tools
            $appUserId: '%env(int:APP_USER_ID)%'
            $appUserLogin: 'env(string:APP_USER_LOGIN)'
            # Telegram Bot API
            $telegramToken: 'env(string:TELEGRAM_BOT_TOKEN)'
            $debugEnabled: '%kernel.debug%'
            # Point API
            $pointDomain: 'env(string:APP_POINT_DOMAIN)'
            $pointScheme: 'env(string:APP_POINT_SCHEME)'
            $pointApiDelay: '%env(int:APP_POINT_API_DELAY)%'
            $pointApiClient: '@app.point.http_client'
            # Crawler API
            $crawlerSecret: 'env(string:APP_CRAWLER_SECRET)'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # HTTP client for Point API
    app.point.http_client:
        class: Symfony\Component\HttpClient\HttpClient
        factory: [null, 'create']
        arguments:
            base_uri: '%point_base_url%'
            timeout: 5.0
