Skobkin\Bundle\PointToolsBundle\DTO\Api\MetaPost:
    exclusion_policy: none
    access_type: public_method
    properties:
        post:
            type: 'Skobkin\Bundle\PointToolsBundle\DTO\Api\Post'
            max_depth: 2
        comments:
            type: 'array<Skobkin\Bundle\PointToolsBundle\DTO\Api\Comment>'
            max_depth: 2
