Skobkin\Bundle\PointToolsBundle\DTO\Api\MetaPost:
    exclusion_policy: none
    properties:
        post:
            serialized_name: 'post'
            type: 'Skobkin\Bundle\PointToolsBundle\DTO\Api\Post'
        comments:
            serialized_name: 'comments'
            type: 'array<Skobkin\Bundle\PointToolsBundle\DTO\Api\Comment>'
