Skobkin\Bundle\PointToolsBundle\DTO\Api\Auth:
    exclusion_policy: none
    access_type: public_method
    properties:
        token:
            type: string
        csRfToken:
            type: string
            serialized_name: 'csrf_token'
        error:
            type: string
